on:
  # Trigger the workflow on push,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - name: Install and Build
      run: |
        npm install
        npm run lint
        npm run test-coverage
        npm run build
        npm run copy-coverage-to-build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
